name: Build

on:
  workflow_run:
    workflows: [Lint]
    types: [completed]

jobs:
  build-backend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Hello world
          run: echo "Halo, jest tam kto?"
  build-frontend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Hello world
          run: echo "Halo, jest tam kto?"

