name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt install python3 python3-pip
          python -m venv venv
          source venv/bin/activate
          python -m pip install -r front-end/requirements_lint.txt


      - name: Run linter
        run: python -m black --check front-end/
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hello world
        run: echo "Halo, jest tam kto?"

