name: Build

on: [push]

permissions:
  contents: read
  packages: write

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install -r back-end/requirements_lint.txt

      - name: Run linter
        run: |
          source venv/bin/activate
          python -m black --check back-end/
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install -r front-end/requirements_lint.txt


      - name: Run linter
        run: |
          source venv/bin/activate
          python -m black --check front-end/

  build-frontend:
      runs-on: ubuntu-latest
      needs: [lint-frontend, lint-backend]
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}        

        - name: Build Docker image
          uses: docker/build-push-action@v6
          with:
            context: ./front-end
            file: ./front-end/Dockerfile
            push: true
            tags: |
              ghcr.io/Pjurkowsky/WUDA:latest
              ghcr.io/Pjurkowsky/WUDA:${{ github.sha }}


  build-backend:
      runs-on: ubuntu-latest
      needs: [lint-frontend, lint-backend]
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
       
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}        
        
        - name: Build Docker image
          uses: docker/build-push-action@v6
          with:
            context: ./back-end
            file: ./back-end/Dockerfile
            push: true
            tags: |
              ghcr.io/Pjurkowsky/WUDA:latest
              ghcr.io/Pjurkowsky/WUDA:${{ github.sha }}

